### ISSUE TITLE
rules_proto broken with Bazel latest release 

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_proto#170] opened 2023-04-20 08:59 UTC
https://buildkite.com/bazel/rules-proto/builds/1640#018796ea-1cec-48fc-99d4-fef35feb22d5
When building with Bazel 6.1.2, we got the following error message:

```
(04:07:05) ERROR: /workdir/tests/rules/proto_descriptor_set/BUILD:10:21: every rule of type proto_descriptor_set implicitly depends upon the target '//third_party/bazel_rules/rules_proto:license', but this target could not be found because of: no such package 'third_party/bazel_rules/rules_proto': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
--
  | - /workdir/third_party/bazel_rules/rules_proto
  | (04:07:05) ERROR: Analysis of target '//tests/rules/proto_descriptor_set:no_protos' failed; build aborted: Analysis failed
```

rules_proto: :ubuntu:[ 20.04 LTS (OpenJDK 11, gcc 9.4.0)](https://buildkite.com/bazel/rules-proto/builds/1640#018796ea-1ce9-4bb5-a4fd-847e9545327d), :darwin:[ (OpenJDK 11, Xcode)](https://buildkite.com/bazel/rules-proto/builds/1640#018796ea-1cec-48fc-99d4-fef35feb22d5), :windows:[ (OpenJDK 11, VS2019)](https://buildkite.com/bazel/rules-proto/builds/1640#018796ea-1cee-4340-be3e-2b45af31644e), :ubuntu:[ 20.04 LTS (OpenJDK 11, gcc 9.4.0)](https://buildkite.com/bazel/rules-proto/builds/1640#018796ea-1cf1-494a-8037-e86f338ac955), :darwin:[ (OpenJDK 11, Xcode)](https://buildkite.com/bazel/rules-proto/builds/1640#018796ea-1cf4-4e90-9e25-3551c04ced99), :windows:[ (OpenJDK 11, VS2019)](https://buildkite.com/bazel/rules-proto/builds/1640#018796ea-1cf6-47d8-abee-9cc4df0d6eea), :ubuntu:[ 20.04 LTS (OpenJDK 11, gcc 9.4.0)](https://buildkite.com/bazel/rules-proto/builds/1640#018796ea-1cf9-49d0-ab0d-9ef831a71546), :darwin:[ (OpenJDK 11, Xcode)](https://buildkite.com/bazel/rules-proto/builds/1640#018796ea-1cfc-4fa4-9770-7d0e5cc0f7f0), :windows:[ (OpenJDK 11, VS2019)](https://buildkite.com/bazel/rules-proto/builds/1640#018796ea-1cfe-40bd-b3d5-fae73472de8a)

CC @meteorcloudy

**Comment by comius** [comment] 2023-04-20 09:29
It's a problem with rules_proto@HEAD, not Bazel.

**Comment by comius** [comment] 2023-04-20 09:30
Duplicate of https://github.com/bazelbuild/rules_proto/issues/167

**Comment by comius** [comment] 2023-08-30 06:07
This was fixed.

**Closed by comius** 2023-08-30 06:07 UTC
Labels: bug, P2
