### ISSUE TITLE
Propagating copts to proto_library

### ISSUE THREAD

**Issue by DavidKorczynski** [bazelbuild/rules_proto#85] opened 2021-03-25 17:15 UTC
Hi, 
I have an issue when declaring a `proto_library` for a given `.proto` file. The `proto_library` will output a rule `XX_cc_proto` which is the one that compiles the generated `.pb.cc` file as far as I can understand. However, I would like to append a set of `copts` to the compilation of the `.pb.cc` file when it happens - and it would be great if these could for example be target specific (varies per `proto_library` target). I am not entirely sure where to do this as the `XX_cc_proto` is generated doing the build process.

**Comment by DavidKorczynski** [comment] 2021-03-25 17:23
This might be a duplicate of https://github.com/bazelbuild/rules_proto/issues/41 

Has any changes happened on this issue?

**Comment by comius** [comment] 2022-02-08 07:51
duplicate of https://github.com/bazelbuild/rules_proto/issues/41

**Closed by comius** 2022-02-08 07:51 UTC
